services:
  tagoio-data-handler:
    container_name: tagoio-data-handler
    image: tagoio-data-handler
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "127.0.0.1:${API_PORT}:${API_PORT}"
    networks:
      - tagoio-data-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    volumes:
      - ./database_files:/src/database_files:rw
    restart: on-failure:1

networks:
  tagoio-data-network:
    name: tagoio_data_network
