from typing import Optional

from pydantic import BaseModel, ConfigDict, EmailStr, Field


class GoogleFormPayload(BaseModel):
    """
    Validates and maps the incoming Google Forms webhook.
    Aliases match the exact string keys generated by the form submission.
    """

    model_config = ConfigDict(populate_by_name=True)
    """Allows populating by the snake_case field name in code, but using the alias for JSON ingestion"""

    user_email: EmailStr = Field(alias="Dirección de correo electrónico")
    company_name: str = Field(alias="Nombre de la Empresa")
    cpo_fiscal_id: str = Field(alias="CIF de la Empresa")
    company_address: str = Field(alias="Dirección de la Empresa")
    contact_phone: str = Field(alias="Teléfono de contacto")
    contact_email: EmailStr = Field(alias="Correo electrónico de contacto")
    manager_name: str = Field(alias="Nombre del Apoderado de la Empresa")
    manager_dni: str = Field(alias="DNI del Apoderado de la Empresa")
    iban: str = Field(alias="IBAN Bancario")
    payment_system: str = Field(alias="Añadir sistema de Pago en los Puntos de Recarga")
    description: str = Field(alias="Descripción del sitio para la instalación.")

    # Optional fields (timestamp might not always be critical for provisioning)
    timestamp: str = Field(default="", alias="Marca temporal")


class CPOProvisioningResponse(BaseModel):
    """
    Response model returned to the Notification Manager after attempting
    to provision a new CPO user and Charging Pool device in TagoIO platform.
    """

    user_created: bool
    device_created: bool
    pool_code: Optional[int] = None
    device_id: Optional[str] = None
    generated_password: Optional[str] = None
    form_data: GoogleFormPayload  # Echoing the validated payload back for the mailer
    error_message: Optional[str] = None
